name: NodeJS CI

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          VERSION=$(echo $GITHUB_REF_NAME | cut -c 2-)
          jq --arg version $VERSION '. + {version: $version}' package.json > tmp.json && mv tmp.json package.json
          VERSION_CODE=$(echo $VERSION | cut -d. -f2-3)
          jq --arg version $VERSION --arg version_code $VERSION_CODE '. + {version: $version, version_code: $version_code}' public/manifest.json > tmp.json && mv tmp.json public/manifest.json
        name: Set Version
      - run: |
          pnpm i
          pnpm build
          curl -L https://github.com/ztelliot/media-cli/releases/latest/download/media-cli -o builds/media-cli
          cd builds
          zip -r MediaMac-$GITHUB_REF_NAME.zip *
        env:
          CI: true
        name: Build & Package
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: builds/MediaMac-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
