name: NodeJS CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          pnpm i
          pnpm build
        env:
          CI: true
        name: Build
      - run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          VERSION_CODE=$(echo $VERSION | cut -d. -f2-3)
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
        name: Extract Version
      - run: |
          jq --arg version $VERSION --arg version_code $VERSION_CODE '. + {version: $version, version_code: $version_code}' public/manifest.json > builds/manifest.json
          curl -L https://github.com/ztelliot/nowplaying-cli/releases/download/latest/nowplaying-cli-${{ matrix.arch }} -o builds/nowplaying-cli
          cd builds
          zip -r MediaMac-$VERSION-${{ matrix.arch }}.zip *
        name: Package
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: builds/MediaMac-${{ env.VERSION }}-${{ matrix.arch }}.zip
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
