name: NodeJS CI

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          pnpm version $GITHUB_REF_NAME --no-git-tag-version
          pnpm i
          pnpm build
        env:
          CI: true
        name: Build & Package
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: MediaMac-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
